import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// ১. TimelineProvider ইম্পোর্ট করুন (পাথটি আপনার প্রজেক্ট অনুযায়ী চেক করে নিন)
import { TimelineProvider } from "@/context/TimelineContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-base-200">
        {/* ২. পুরো অ্যাপকে TimelineProvider দিয়ে র‍্যাপ করুন */}
        <TimelineProvider>
          <Navbar />
          <main className="bg-base-200">
            {children}
          </main>
          <Footer />
        </TimelineProvider>
      </body>
    </html>
  );
}